// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WhatsappScrapper.DataAccess.Context;

#nullable disable

namespace WhatsappScrapper.DataAccess.Migrations.UserDB
{
    [DbContext(typeof(UserDBContext))]
    [Migration("20230501184338_FillCountries")]
    partial class FillCountries
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WhatsAppScrapper.Models.DataModels.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhonePrefix")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF",
                            Name = "Afghanistan",
                            PhonePrefix = "93"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AL",
                            Name = "Albania",
                            PhonePrefix = "355"
                        },
                        new
                        {
                            Id = 3,
                            Code = "DZ",
                            Name = "Algeria",
                            PhonePrefix = "213"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AS",
                            Name = "American Samoa",
                            PhonePrefix = "1684"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AD",
                            Name = "Andorra",
                            PhonePrefix = "376"
                        },
                        new
                        {
                            Id = 6,
                            Code = "AO",
                            Name = "Angola",
                            PhonePrefix = "244"
                        },
                        new
                        {
                            Id = 7,
                            Code = "AI",
                            Name = "Anguilla",
                            PhonePrefix = "1264"
                        },
                        new
                        {
                            Id = 8,
                            Code = "AQ",
                            Name = "Antarctica",
                            PhonePrefix = "672"
                        },
                        new
                        {
                            Id = 9,
                            Code = "AG",
                            Name = "Antigua and Barbuda",
                            PhonePrefix = "1268"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AR",
                            Name = "Argentina",
                            PhonePrefix = "54"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AM",
                            Name = "Armenia",
                            PhonePrefix = "374"
                        },
                        new
                        {
                            Id = 12,
                            Code = "AW",
                            Name = "Aruba",
                            PhonePrefix = "297"
                        },
                        new
                        {
                            Id = 13,
                            Code = "AU",
                            Name = "Australia",
                            PhonePrefix = "61"
                        },
                        new
                        {
                            Id = 14,
                            Code = "AT",
                            Name = "Austria",
                            PhonePrefix = "43"
                        },
                        new
                        {
                            Id = 15,
                            Code = "AZ",
                            Name = "Azerbaijan",
                            PhonePrefix = "994"
                        },
                        new
                        {
                            Id = 16,
                            Code = "BS",
                            Name = "Bahamas",
                            PhonePrefix = "1242"
                        },
                        new
                        {
                            Id = 17,
                            Code = "BH",
                            Name = "Bahrain",
                            PhonePrefix = "973"
                        },
                        new
                        {
                            Id = 18,
                            Code = "BD",
                            Name = "Bangladesh",
                            PhonePrefix = "880"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BB",
                            Name = "Barbados",
                            PhonePrefix = "1246"
                        },
                        new
                        {
                            Id = 20,
                            Code = "BY",
                            Name = "Belarus",
                            PhonePrefix = "375"
                        },
                        new
                        {
                            Id = 21,
                            Code = "BE",
                            Name = "Belgium",
                            PhonePrefix = "32"
                        },
                        new
                        {
                            Id = 22,
                            Code = "BZ",
                            Name = "Belize",
                            PhonePrefix = "501"
                        },
                        new
                        {
                            Id = 23,
                            Code = "BJ",
                            Name = "Benin",
                            PhonePrefix = "229"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BM",
                            Name = "Bermuda",
                            PhonePrefix = "1441"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BT",
                            Name = "Bhutan",
                            PhonePrefix = "975"
                        },
                        new
                        {
                            Id = 26,
                            Code = "BO",
                            Name = "Bolivia",
                            PhonePrefix = "591"
                        },
                        new
                        {
                            Id = 27,
                            Code = "BA",
                            Name = "Bosnia and Herzegovina",
                            PhonePrefix = "387"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BW",
                            Name = "Botswana",
                            PhonePrefix = "267"
                        },
                        new
                        {
                            Id = 29,
                            Code = "BV",
                            Name = "Bouvet Island",
                            PhonePrefix = ""
                        },
                        new
                        {
                            Id = 30,
                            Code = "BR",
                            Name = "Brazil",
                            PhonePrefix = "55"
                        },
                        new
                        {
                            Id = 31,
                            Code = "IO",
                            Name = "British Indian Ocean Territory",
                            PhonePrefix = "246"
                        },
                        new
                        {
                            Id = 32,
                            Code = "BN",
                            Name = "Brunei Darussalam",
                            PhonePrefix = "673"
                        },
                        new
                        {
                            Id = 33,
                            Code = "BG",
                            Name = "Bulgaria",
                            PhonePrefix = "359"
                        },
                        new
                        {
                            Id = 34,
                            Code = "BF",
                            Name = "Burkina Faso",
                            PhonePrefix = "226"
                        },
                        new
                        {
                            Id = 35,
                            Code = "BI",
                            Name = "Burundi",
                            PhonePrefix = "257"
                        },
                        new
                        {
                            Id = 36,
                            Code = "KH",
                            Name = "Cambodia",
                            PhonePrefix = "855"
                        },
                        new
                        {
                            Id = 37,
                            Code = "CM",
                            Name = "Cameroon",
                            PhonePrefix = "237"
                        },
                        new
                        {
                            Id = 38,
                            Code = "CA",
                            Name = "Canada",
                            PhonePrefix = "1"
                        },
                        new
                        {
                            Id = 39,
                            Code = "CV",
                            Name = "Cape Verde",
                            PhonePrefix = "238"
                        },
                        new
                        {
                            Id = 40,
                            Code = "KY",
                            Name = "Cayman Islands",
                            PhonePrefix = "1345"
                        },
                        new
                        {
                            Id = 41,
                            Code = "CF",
                            Name = "Central African Republic",
                            PhonePrefix = "236"
                        },
                        new
                        {
                            Id = 42,
                            Code = "TD",
                            Name = "Chad",
                            PhonePrefix = "235"
                        },
                        new
                        {
                            Id = 43,
                            Code = "CL",
                            Name = "Chile",
                            PhonePrefix = "56"
                        },
                        new
                        {
                            Id = 44,
                            Code = "CN",
                            Name = "China",
                            PhonePrefix = "86"
                        },
                        new
                        {
                            Id = 45,
                            Code = "CX",
                            Name = "Christmas Island",
                            PhonePrefix = "61"
                        },
                        new
                        {
                            Id = 46,
                            Code = "CC",
                            Name = "Cocos (Keeling) Islands",
                            PhonePrefix = "61"
                        },
                        new
                        {
                            Id = 47,
                            Code = "CO",
                            Name = "Colombia",
                            PhonePrefix = "57"
                        },
                        new
                        {
                            Id = 48,
                            Code = "KM",
                            Name = "Comoros",
                            PhonePrefix = "269"
                        },
                        new
                        {
                            Id = 49,
                            Code = "CG",
                            Name = "Congo",
                            PhonePrefix = "242"
                        },
                        new
                        {
                            Id = 50,
                            Code = "CD",
                            Name = "Congo, The Democratic Republic of the",
                            PhonePrefix = "243"
                        },
                        new
                        {
                            Id = 51,
                            Code = "CK",
                            Name = "Cook Islands",
                            PhonePrefix = "682"
                        },
                        new
                        {
                            Id = 52,
                            Code = "CR",
                            Name = "Costa Rica",
                            PhonePrefix = "506"
                        },
                        new
                        {
                            Id = 53,
                            Code = "CI",
                            Name = "Cote D\"Ivoire",
                            PhonePrefix = "225"
                        },
                        new
                        {
                            Id = 54,
                            Code = "HR",
                            Name = "Croatia",
                            PhonePrefix = "385"
                        },
                        new
                        {
                            Id = 55,
                            Code = "CU",
                            Name = "Cuba",
                            PhonePrefix = "53"
                        },
                        new
                        {
                            Id = 56,
                            Code = "CY",
                            Name = "Cyprus",
                            PhonePrefix = "357"
                        },
                        new
                        {
                            Id = 57,
                            Code = "CZ",
                            Name = "Czech Republic",
                            PhonePrefix = "420"
                        },
                        new
                        {
                            Id = 58,
                            Code = "DK",
                            Name = "Denmark",
                            PhonePrefix = "45"
                        },
                        new
                        {
                            Id = 59,
                            Code = "DJ",
                            Name = "Djibouti",
                            PhonePrefix = "253"
                        },
                        new
                        {
                            Id = 60,
                            Code = "DM",
                            Name = "Dominica",
                            PhonePrefix = "1767"
                        },
                        new
                        {
                            Id = 61,
                            Code = "DO",
                            Name = "Dominican Republic",
                            PhonePrefix = "1"
                        },
                        new
                        {
                            Id = 62,
                            Code = "EC",
                            Name = "Ecuador",
                            PhonePrefix = "593"
                        },
                        new
                        {
                            Id = 63,
                            Code = "EG",
                            Name = "Egypt",
                            PhonePrefix = "20"
                        },
                        new
                        {
                            Id = 64,
                            Code = "SV",
                            Name = "El Salvador",
                            PhonePrefix = "503"
                        },
                        new
                        {
                            Id = 65,
                            Code = "GQ",
                            Name = "Equatorial Guinea",
                            PhonePrefix = "240"
                        },
                        new
                        {
                            Id = 66,
                            Code = "ER",
                            Name = "Eritrea",
                            PhonePrefix = "291"
                        },
                        new
                        {
                            Id = 67,
                            Code = "EE",
                            Name = "Estonia",
                            PhonePrefix = "372"
                        },
                        new
                        {
                            Id = 68,
                            Code = "ET",
                            Name = "Ethiopia",
                            PhonePrefix = "251"
                        },
                        new
                        {
                            Id = 69,
                            Code = "FK",
                            Name = "Falkland Islands (Malvinas)",
                            PhonePrefix = "500"
                        },
                        new
                        {
                            Id = 70,
                            Code = "FO",
                            Name = "Faroe Islands",
                            PhonePrefix = "298"
                        },
                        new
                        {
                            Id = 71,
                            Code = "FJ",
                            Name = "Fiji",
                            PhonePrefix = "679"
                        },
                        new
                        {
                            Id = 72,
                            Code = "FI",
                            Name = "Finland",
                            PhonePrefix = "358"
                        },
                        new
                        {
                            Id = 73,
                            Code = "FR",
                            Name = "France",
                            PhonePrefix = "33"
                        },
                        new
                        {
                            Id = 74,
                            Code = "GF",
                            Name = "French Guiana",
                            PhonePrefix = "594"
                        },
                        new
                        {
                            Id = 75,
                            Code = "PF",
                            Name = "French Polynesia",
                            PhonePrefix = "689"
                        },
                        new
                        {
                            Id = 76,
                            Code = "TF",
                            Name = "French Southern Territories",
                            PhonePrefix = ""
                        },
                        new
                        {
                            Id = 77,
                            Code = "GA",
                            Name = "Gabon",
                            PhonePrefix = "241"
                        },
                        new
                        {
                            Id = 78,
                            Code = "GM",
                            Name = "Gambia",
                            PhonePrefix = "220"
                        },
                        new
                        {
                            Id = 79,
                            Code = "GE",
                            Name = "Georgia",
                            PhonePrefix = "995"
                        },
                        new
                        {
                            Id = 80,
                            Code = "DE",
                            Name = "Germany",
                            PhonePrefix = "49"
                        },
                        new
                        {
                            Id = 81,
                            Code = "GH",
                            Name = "Ghana",
                            PhonePrefix = "233"
                        },
                        new
                        {
                            Id = 82,
                            Code = "GI",
                            Name = "Gibraltar",
                            PhonePrefix = "350"
                        },
                        new
                        {
                            Id = 83,
                            Code = "GR",
                            Name = "Greece",
                            PhonePrefix = "30"
                        },
                        new
                        {
                            Id = 84,
                            Code = "GL",
                            Name = "Greenland",
                            PhonePrefix = "299"
                        },
                        new
                        {
                            Id = 85,
                            Code = "GD",
                            Name = "Grenada",
                            PhonePrefix = "1"
                        },
                        new
                        {
                            Id = 86,
                            Code = "GP",
                            Name = "Guadeloupe",
                            PhonePrefix = "590"
                        },
                        new
                        {
                            Id = 87,
                            Code = "GU",
                            Name = "Guam",
                            PhonePrefix = "1671"
                        },
                        new
                        {
                            Id = 88,
                            Code = "GT",
                            Name = "Guatemala",
                            PhonePrefix = "502"
                        },
                        new
                        {
                            Id = 89,
                            Code = "GG",
                            Name = "Guernsey",
                            PhonePrefix = "44"
                        },
                        new
                        {
                            Id = 90,
                            Code = "GN",
                            Name = "Guinea",
                            PhonePrefix = "224"
                        },
                        new
                        {
                            Id = 91,
                            Code = "GW",
                            Name = "Guinea-Bissau",
                            PhonePrefix = "245"
                        },
                        new
                        {
                            Id = 92,
                            Code = "GY",
                            Name = "Guyana",
                            PhonePrefix = "592"
                        },
                        new
                        {
                            Id = 93,
                            Code = "HT",
                            Name = "Haiti",
                            PhonePrefix = "509"
                        },
                        new
                        {
                            Id = 94,
                            Code = "HM",
                            Name = "Heard Island and Mcdonald Islands",
                            PhonePrefix = ""
                        },
                        new
                        {
                            Id = 95,
                            Code = "VA",
                            Name = "Holy See (Vatican City State)",
                            PhonePrefix = "39"
                        },
                        new
                        {
                            Id = 96,
                            Code = "HN",
                            Name = "Honduras",
                            PhonePrefix = "504"
                        },
                        new
                        {
                            Id = 97,
                            Code = "HK",
                            Name = "Hong Kong",
                            PhonePrefix = "852"
                        },
                        new
                        {
                            Id = 98,
                            Code = "HU",
                            Name = "Hungary",
                            PhonePrefix = "36"
                        },
                        new
                        {
                            Id = 99,
                            Code = "IS",
                            Name = "Iceland",
                            PhonePrefix = "354"
                        },
                        new
                        {
                            Id = 100,
                            Code = "IN",
                            Name = "India",
                            PhonePrefix = "91"
                        },
                        new
                        {
                            Id = 101,
                            Code = "ID",
                            Name = "Indonesia",
                            PhonePrefix = "62"
                        },
                        new
                        {
                            Id = 102,
                            Code = "IR",
                            Name = "Iran, Islamic Republic Of",
                            PhonePrefix = "98"
                        },
                        new
                        {
                            Id = 103,
                            Code = "IQ",
                            Name = "Iraq",
                            PhonePrefix = "964"
                        },
                        new
                        {
                            Id = 104,
                            Code = "IE",
                            Name = "Ireland",
                            PhonePrefix = "353"
                        },
                        new
                        {
                            Id = 105,
                            Code = "IM",
                            Name = "Isle of Man",
                            PhonePrefix = "44"
                        },
                        new
                        {
                            Id = 106,
                            Code = "IL",
                            Name = "Israel",
                            PhonePrefix = "972"
                        },
                        new
                        {
                            Id = 107,
                            Code = "IT",
                            Name = "Italy",
                            PhonePrefix = "39"
                        },
                        new
                        {
                            Id = 108,
                            Code = "JM",
                            Name = "Jamaica",
                            PhonePrefix = "1"
                        },
                        new
                        {
                            Id = 109,
                            Code = "JP",
                            Name = "Japan",
                            PhonePrefix = "81"
                        },
                        new
                        {
                            Id = 110,
                            Code = "JE",
                            Name = "Jersey",
                            PhonePrefix = "44"
                        },
                        new
                        {
                            Id = 111,
                            Code = "JO",
                            Name = "Jordan",
                            PhonePrefix = "962"
                        },
                        new
                        {
                            Id = 112,
                            Code = "KZ",
                            Name = "Kazakhstan",
                            PhonePrefix = "7"
                        },
                        new
                        {
                            Id = 113,
                            Code = "KE",
                            Name = "Kenya",
                            PhonePrefix = "254"
                        },
                        new
                        {
                            Id = 114,
                            Code = "KI",
                            Name = "Kiribati",
                            PhonePrefix = "686"
                        },
                        new
                        {
                            Id = 115,
                            Code = "KP",
                            Name = "Korea, Democratic People\"S Republic of",
                            PhonePrefix = "850"
                        },
                        new
                        {
                            Id = 116,
                            Code = "KR",
                            Name = "Korea, Republic of",
                            PhonePrefix = "82"
                        },
                        new
                        {
                            Id = 117,
                            Code = "KW",
                            Name = "Kuwait",
                            PhonePrefix = "965"
                        },
                        new
                        {
                            Id = 118,
                            Code = "KG",
                            Name = "Kyrgyzstan",
                            PhonePrefix = "996"
                        },
                        new
                        {
                            Id = 119,
                            Code = "LA",
                            Name = "Lao People\"S Democratic Republic",
                            PhonePrefix = "856"
                        },
                        new
                        {
                            Id = 120,
                            Code = "LV",
                            Name = "Latvia",
                            PhonePrefix = "371"
                        },
                        new
                        {
                            Id = 121,
                            Code = "LB",
                            Name = "Lebanon",
                            PhonePrefix = "961"
                        },
                        new
                        {
                            Id = 122,
                            Code = "LS",
                            Name = "Lesotho",
                            PhonePrefix = "266"
                        },
                        new
                        {
                            Id = 123,
                            Code = "LR",
                            Name = "Liberia",
                            PhonePrefix = "231"
                        },
                        new
                        {
                            Id = 124,
                            Code = "LY",
                            Name = "Libyan Arab Jamahiriya",
                            PhonePrefix = "218"
                        },
                        new
                        {
                            Id = 125,
                            Code = "LI",
                            Name = "Liechtenstein",
                            PhonePrefix = "423"
                        },
                        new
                        {
                            Id = 126,
                            Code = "LT",
                            Name = "Lithuania",
                            PhonePrefix = "370"
                        },
                        new
                        {
                            Id = 127,
                            Code = "LU",
                            Name = "Luxembourg",
                            PhonePrefix = "352"
                        },
                        new
                        {
                            Id = 128,
                            Code = "MO",
                            Name = "Macao",
                            PhonePrefix = "853"
                        },
                        new
                        {
                            Id = 129,
                            Code = "MK",
                            Name = "Macedonia, The Former Yugoslav Republic of",
                            PhonePrefix = "389"
                        },
                        new
                        {
                            Id = 130,
                            Code = "MG",
                            Name = "Madagascar",
                            PhonePrefix = "261"
                        },
                        new
                        {
                            Id = 131,
                            Code = "MW",
                            Name = "Malawi",
                            PhonePrefix = "265"
                        },
                        new
                        {
                            Id = 132,
                            Code = "MY",
                            Name = "Malaysia",
                            PhonePrefix = "60"
                        },
                        new
                        {
                            Id = 133,
                            Code = "MV",
                            Name = "Maldives",
                            PhonePrefix = "960"
                        },
                        new
                        {
                            Id = 134,
                            Code = "ML",
                            Name = "Mali",
                            PhonePrefix = "223"
                        },
                        new
                        {
                            Id = 135,
                            Code = "MT",
                            Name = "Malta",
                            PhonePrefix = "356"
                        },
                        new
                        {
                            Id = 136,
                            Code = "MH",
                            Name = "Marshall Islands",
                            PhonePrefix = "692"
                        },
                        new
                        {
                            Id = 137,
                            Code = "MQ",
                            Name = "Martinique",
                            PhonePrefix = "596"
                        },
                        new
                        {
                            Id = 138,
                            Code = "MR",
                            Name = "Mauritania",
                            PhonePrefix = "222"
                        },
                        new
                        {
                            Id = 139,
                            Code = "MU",
                            Name = "Mauritius",
                            PhonePrefix = "230"
                        },
                        new
                        {
                            Id = 140,
                            Code = "YT",
                            Name = "Mayotte",
                            PhonePrefix = "262"
                        },
                        new
                        {
                            Id = 141,
                            Code = "MX",
                            Name = "Mexico",
                            PhonePrefix = "52"
                        },
                        new
                        {
                            Id = 142,
                            Code = "FM",
                            Name = "Micronesia, Federated States of",
                            PhonePrefix = "691"
                        },
                        new
                        {
                            Id = 143,
                            Code = "MD",
                            Name = "Moldova, Republic of",
                            PhonePrefix = "373"
                        },
                        new
                        {
                            Id = 144,
                            Code = "MC",
                            Name = "Monaco",
                            PhonePrefix = "377"
                        },
                        new
                        {
                            Id = 145,
                            Code = "MN",
                            Name = "Mongolia",
                            PhonePrefix = "976"
                        },
                        new
                        {
                            Id = 146,
                            Code = "MS",
                            Name = "Montserrat",
                            PhonePrefix = "1664"
                        },
                        new
                        {
                            Id = 147,
                            Code = "MA",
                            Name = "Morocco",
                            PhonePrefix = "212"
                        },
                        new
                        {
                            Id = 148,
                            Code = "MZ",
                            Name = "Mozambique",
                            PhonePrefix = "258"
                        },
                        new
                        {
                            Id = 149,
                            Code = "MM",
                            Name = "Myanmar",
                            PhonePrefix = "95"
                        },
                        new
                        {
                            Id = 150,
                            Code = "NA",
                            Name = "Namibia",
                            PhonePrefix = "264"
                        },
                        new
                        {
                            Id = 151,
                            Code = "NR",
                            Name = "Nauru",
                            PhonePrefix = "674"
                        },
                        new
                        {
                            Id = 152,
                            Code = "NP",
                            Name = "Nepal",
                            PhonePrefix = "977"
                        },
                        new
                        {
                            Id = 153,
                            Code = "NL",
                            Name = "Netherlands",
                            PhonePrefix = "31"
                        },
                        new
                        {
                            Id = 154,
                            Code = "AN",
                            Name = "Netherlands Antilles",
                            PhonePrefix = "599"
                        },
                        new
                        {
                            Id = 155,
                            Code = "NC",
                            Name = "New Caledonia",
                            PhonePrefix = "687"
                        },
                        new
                        {
                            Id = 156,
                            Code = "NZ",
                            Name = "New Zealand",
                            PhonePrefix = "64"
                        },
                        new
                        {
                            Id = 157,
                            Code = "NI",
                            Name = "Nicaragua",
                            PhonePrefix = "505"
                        },
                        new
                        {
                            Id = 158,
                            Code = "NE",
                            Name = "Niger",
                            PhonePrefix = "227"
                        },
                        new
                        {
                            Id = 159,
                            Code = "NG",
                            Name = "Nigeria",
                            PhonePrefix = "234"
                        },
                        new
                        {
                            Id = 160,
                            Code = "NU",
                            Name = "Niue",
                            PhonePrefix = "683"
                        },
                        new
                        {
                            Id = 161,
                            Code = "NF",
                            Name = "Norfolk Island",
                            PhonePrefix = "672"
                        },
                        new
                        {
                            Id = 162,
                            Code = "MP",
                            Name = "Northern Mariana Islands",
                            PhonePrefix = "1670"
                        },
                        new
                        {
                            Id = 163,
                            Code = "NO",
                            Name = "Norway",
                            PhonePrefix = "47"
                        },
                        new
                        {
                            Id = 164,
                            Code = "OM",
                            Name = "Oman",
                            PhonePrefix = "968"
                        },
                        new
                        {
                            Id = 165,
                            Code = "PK",
                            Name = "Pakistan",
                            PhonePrefix = "92"
                        },
                        new
                        {
                            Id = 166,
                            Code = "PW",
                            Name = "Palau",
                            PhonePrefix = "680"
                        },
                        new
                        {
                            Id = 167,
                            Code = "PS",
                            Name = "Palestinian Territory, Occupied",
                            PhonePrefix = "970"
                        },
                        new
                        {
                            Id = 168,
                            Code = "PA",
                            Name = "Panama",
                            PhonePrefix = "507"
                        },
                        new
                        {
                            Id = 169,
                            Code = "PG",
                            Name = "Papua New Guinea",
                            PhonePrefix = "675"
                        },
                        new
                        {
                            Id = 170,
                            Code = "PY",
                            Name = "Paraguay",
                            PhonePrefix = "595"
                        },
                        new
                        {
                            Id = 171,
                            Code = "PE",
                            Name = "Peru",
                            PhonePrefix = "51"
                        },
                        new
                        {
                            Id = 172,
                            Code = "PH",
                            Name = "Philippines",
                            PhonePrefix = "63"
                        },
                        new
                        {
                            Id = 173,
                            Code = "PN",
                            Name = "Pitcairn",
                            PhonePrefix = "870"
                        },
                        new
                        {
                            Id = 174,
                            Code = "PL",
                            Name = "Poland",
                            PhonePrefix = "48"
                        },
                        new
                        {
                            Id = 175,
                            Code = "PT",
                            Name = "Portugal",
                            PhonePrefix = "351"
                        },
                        new
                        {
                            Id = 176,
                            Code = "PR",
                            Name = "Puerto Rico",
                            PhonePrefix = "1787"
                        },
                        new
                        {
                            Id = 177,
                            Code = "QA",
                            Name = "Qatar",
                            PhonePrefix = "974"
                        },
                        new
                        {
                            Id = 178,
                            Code = "RE",
                            Name = "Reunion",
                            PhonePrefix = "262"
                        },
                        new
                        {
                            Id = 179,
                            Code = "RO",
                            Name = "Romania",
                            PhonePrefix = "40"
                        },
                        new
                        {
                            Id = 180,
                            Code = "RU",
                            Name = "Russian Federation",
                            PhonePrefix = "7"
                        },
                        new
                        {
                            Id = 181,
                            Code = "RW",
                            Name = "RWANDA",
                            PhonePrefix = "250"
                        },
                        new
                        {
                            Id = 182,
                            Code = "SH",
                            Name = "Saint Helena",
                            PhonePrefix = "290"
                        },
                        new
                        {
                            Id = 183,
                            Code = "KN",
                            Name = "Saint Kitts and Nevis",
                            PhonePrefix = "1869"
                        },
                        new
                        {
                            Id = 184,
                            Code = "LC",
                            Name = "Saint Lucia",
                            PhonePrefix = "1758"
                        },
                        new
                        {
                            Id = 185,
                            Code = "PM",
                            Name = "Saint Pierre and Miquelon",
                            PhonePrefix = "508"
                        },
                        new
                        {
                            Id = 186,
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines",
                            PhonePrefix = "1784"
                        },
                        new
                        {
                            Id = 187,
                            Code = "WS",
                            Name = "Samoa",
                            PhonePrefix = "685"
                        },
                        new
                        {
                            Id = 188,
                            Code = "SM",
                            Name = "San Marino",
                            PhonePrefix = "378"
                        },
                        new
                        {
                            Id = 189,
                            Code = "ST",
                            Name = "Sao Tome and Principe",
                            PhonePrefix = "239"
                        },
                        new
                        {
                            Id = 190,
                            Code = "SA",
                            Name = "Saudi Arabia",
                            PhonePrefix = "966"
                        },
                        new
                        {
                            Id = 191,
                            Code = "SN",
                            Name = "Senegal",
                            PhonePrefix = "221"
                        },
                        new
                        {
                            Id = 192,
                            Code = "CS",
                            Name = "Serbia and Montenegro",
                            PhonePrefix = "381"
                        },
                        new
                        {
                            Id = 193,
                            Code = "SC",
                            Name = "Seychelles",
                            PhonePrefix = "248"
                        },
                        new
                        {
                            Id = 194,
                            Code = "SL",
                            Name = "Sierra Leone",
                            PhonePrefix = "232"
                        },
                        new
                        {
                            Id = 195,
                            Code = "SG",
                            Name = "Singapore",
                            PhonePrefix = "65"
                        },
                        new
                        {
                            Id = 196,
                            Code = "SK",
                            Name = "Slovakia",
                            PhonePrefix = "421"
                        },
                        new
                        {
                            Id = 197,
                            Code = "SI",
                            Name = "Slovenia",
                            PhonePrefix = "386"
                        },
                        new
                        {
                            Id = 198,
                            Code = "SB",
                            Name = "Solomon Islands",
                            PhonePrefix = "677"
                        },
                        new
                        {
                            Id = 199,
                            Code = "SO",
                            Name = "Somalia",
                            PhonePrefix = "252"
                        },
                        new
                        {
                            Id = 200,
                            Code = "ZA",
                            Name = "South Africa",
                            PhonePrefix = "27"
                        },
                        new
                        {
                            Id = 201,
                            Code = "GS",
                            Name = "South Georgia and the South Sandwich Islands",
                            PhonePrefix = ""
                        },
                        new
                        {
                            Id = 202,
                            Code = "ES",
                            Name = "Spain",
                            PhonePrefix = "34"
                        },
                        new
                        {
                            Id = 203,
                            Code = "LK",
                            Name = "Sri Lanka",
                            PhonePrefix = "94"
                        },
                        new
                        {
                            Id = 204,
                            Code = "SD",
                            Name = "Sudan",
                            PhonePrefix = "249"
                        },
                        new
                        {
                            Id = 205,
                            Code = "SR",
                            Name = "Suriname",
                            PhonePrefix = "597"
                        },
                        new
                        {
                            Id = 206,
                            Code = "SJ",
                            Name = "Svalbard and Jan Mayen",
                            PhonePrefix = "47"
                        },
                        new
                        {
                            Id = 207,
                            Code = "SZ",
                            Name = "Swaziland",
                            PhonePrefix = "268"
                        },
                        new
                        {
                            Id = 208,
                            Code = "SE",
                            Name = "Sweden",
                            PhonePrefix = "46"
                        },
                        new
                        {
                            Id = 209,
                            Code = "CH",
                            Name = "Switzerland",
                            PhonePrefix = "41"
                        },
                        new
                        {
                            Id = 210,
                            Code = "SY",
                            Name = "Syrian Arab Republic",
                            PhonePrefix = "963"
                        },
                        new
                        {
                            Id = 211,
                            Code = "TW",
                            Name = "Taiwan, Province of China",
                            PhonePrefix = "886"
                        },
                        new
                        {
                            Id = 212,
                            Code = "TJ",
                            Name = "Tajikistan",
                            PhonePrefix = "992"
                        },
                        new
                        {
                            Id = 213,
                            Code = "TZ",
                            Name = "Tanzania, United Republic of",
                            PhonePrefix = "255"
                        },
                        new
                        {
                            Id = 214,
                            Code = "TH",
                            Name = "Thailand",
                            PhonePrefix = "66"
                        },
                        new
                        {
                            Id = 215,
                            Code = "TL",
                            Name = "Timor-Leste",
                            PhonePrefix = "670"
                        },
                        new
                        {
                            Id = 216,
                            Code = "TG",
                            Name = "Togo",
                            PhonePrefix = "228"
                        },
                        new
                        {
                            Id = 217,
                            Code = "TK",
                            Name = "Tokelau",
                            PhonePrefix = "690"
                        },
                        new
                        {
                            Id = 218,
                            Code = "TO",
                            Name = "Tonga",
                            PhonePrefix = "676"
                        },
                        new
                        {
                            Id = 219,
                            Code = "TT",
                            Name = "Trinidad and Tobago",
                            PhonePrefix = "1868"
                        },
                        new
                        {
                            Id = 220,
                            Code = "TN",
                            Name = "Tunisia",
                            PhonePrefix = "216"
                        },
                        new
                        {
                            Id = 221,
                            Code = "TR",
                            Name = "Turkey",
                            PhonePrefix = "90"
                        },
                        new
                        {
                            Id = 222,
                            Code = "TM",
                            Name = "Turkmenistan",
                            PhonePrefix = "993"
                        },
                        new
                        {
                            Id = 223,
                            Code = "TC",
                            Name = "Turks and Caicos Islands",
                            PhonePrefix = "1649"
                        },
                        new
                        {
                            Id = 224,
                            Code = "TV",
                            Name = "Tuvalu",
                            PhonePrefix = "688"
                        },
                        new
                        {
                            Id = 225,
                            Code = "UG",
                            Name = "Uganda",
                            PhonePrefix = "256"
                        },
                        new
                        {
                            Id = 226,
                            Code = "UA",
                            Name = "Ukraine",
                            PhonePrefix = "380"
                        },
                        new
                        {
                            Id = 227,
                            Code = "AE",
                            Name = "United Arab Emirates",
                            PhonePrefix = "971"
                        },
                        new
                        {
                            Id = 228,
                            Code = "GB",
                            Name = "United Kingdom",
                            PhonePrefix = "44"
                        },
                        new
                        {
                            Id = 229,
                            Code = "US",
                            Name = "United States",
                            PhonePrefix = "1"
                        },
                        new
                        {
                            Id = 230,
                            Code = "UM",
                            Name = "United States Minor Outlying Islands",
                            PhonePrefix = ""
                        },
                        new
                        {
                            Id = 231,
                            Code = "UY",
                            Name = "Uruguay",
                            PhonePrefix = "598"
                        },
                        new
                        {
                            Id = 232,
                            Code = "UZ",
                            Name = "Uzbekistan",
                            PhonePrefix = "998"
                        },
                        new
                        {
                            Id = 233,
                            Code = "VU",
                            Name = "Vanuatu",
                            PhonePrefix = "678"
                        },
                        new
                        {
                            Id = 234,
                            Code = "VE",
                            Name = "Venezuela",
                            PhonePrefix = "58"
                        },
                        new
                        {
                            Id = 235,
                            Code = "VN",
                            Name = "Viet Nam",
                            PhonePrefix = "84"
                        },
                        new
                        {
                            Id = 236,
                            Code = "VG",
                            Name = "Virgin Islands, British",
                            PhonePrefix = "1284"
                        },
                        new
                        {
                            Id = 237,
                            Code = "VI",
                            Name = "Virgin Islands, U.S.",
                            PhonePrefix = "1340"
                        },
                        new
                        {
                            Id = 238,
                            Code = "WF",
                            Name = "Wallis and Futuna",
                            PhonePrefix = "681"
                        },
                        new
                        {
                            Id = 239,
                            Code = "EH",
                            Name = "Western Sahara",
                            PhonePrefix = "212"
                        },
                        new
                        {
                            Id = 240,
                            Code = "YE",
                            Name = "Yemen",
                            PhonePrefix = "967"
                        },
                        new
                        {
                            Id = 241,
                            Code = "ZM",
                            Name = "Zambia",
                            PhonePrefix = "260"
                        },
                        new
                        {
                            Id = 242,
                            Code = "ZW",
                            Name = "Zimbabwe",
                            PhonePrefix = "263"
                        });
                });

            modelBuilder.Entity("WhatsAppScrapper.Models.DataModels.PhoneBook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UTCCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ZoneId");

                    b.HasIndex("Name", "LastName", "Phone", "UserId");

                    b.ToTable("PhoneBooks");
                });

            modelBuilder.Entity("WhatsAppScrapper.Models.DataModels.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Code", "Name")
                        .IsUnique();

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("WhatsAppScrapper.Models.DataModels.PhoneBook", b =>
                {
                    b.HasOne("WhatsAppScrapper.Models.DataModels.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("WhatsAppScrapper.Models.DataModels.Zone", "Zone")
                        .WithMany()
                        .HasForeignKey("ZoneId");

                    b.Navigation("Country");

                    b.Navigation("Zone");
                });
#pragma warning restore 612, 618
        }
    }
}
